### ISSUE TITLE
The second person entering a scene may see it differently than the scene creator.

### ISSUE THREAD

**Issue by carlfravel** [decentraland/editor-legacy#16]
When 2nd person enters a new scene, the boilerplate objects might change from where the scene creator has them

Steps:
Dave created a new scene (on mac)
Carl enters the scene
Carl sees the bottom blue bar superimposed with the top one (wrongly located)

This might be an issue pertaining to persistence problems.
For example, Carl's PC browser cache (Chrome) might be remembering the location of a boilerplate component from an previously viewed or edited scene.

**Comment by cfravel** [comment]
#23 is a much clearer writeup of specific steps and problems.
#16 is a weak duplicate, so i'm closing it.
