### ISSUE TITLE
The positions of the scene light isn't restored from the previous scene save

### ISSUE THREAD

**Issue by cfravel** [decentraland/editor-legacy#31]
Open Loader
Select land (buy it if you don't own it).
Open editor on your land
Place some object in the scene.
Move the Y position of the <a-entity [object] [light] [material]> to 50m (higher in the sky)
Publish scene.
Close editor
Reopen Editor from the same land selection
// expected: the light remains where you put it
// actual: the light is back at the default position of 10,10,10

**Comment by eordano** [comment]
This is by design. We're working on defining how users should be able to alter both the sky box and the global lighting, but this is not a priority right now.
